version: "3.7"

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: >
      sh -c "python3 ./manage.py migrate &&
             python manage.py runserver -b 0.0.0.0:8000"
    env_file:
      - ./.env